name: unit tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: run unittest
        run: make unittest
        env:
          GO_FLAGS: -mod=vendor
          GO111MODULE: on
